language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install: pip install tox
script:
    - TOXENV=$(tox --listenvs | grep "py${TRAVIS_PYTHON_VERSION/./}-" | tr '\n' ',')
    - export TOXENV
    - tox
